version: "3.3"

services:
  postgres:
    image: postgres:latest

    container_name: postgres
    
    restart: always
    
    environment:
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "django_user"
      POSTGRES_PASSWORD: "password"
      #POSTGRES_HOST_AUTH_METHOD: trust
    
    volumes:
      - .:/docker-entrypoint-initdb.d
    
    ports:
      - "5432:5432"
    
    networks:
      - app-network
    

  nginx:
    
    image: nginx:latest
    
    container_name: nginx
    
    
    restart: always
    
    volumes:
      - ./nginx/static:/home/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - "80:80" 
    
    networks:
      - app-network

  django_app:
    
    build:
      context: django_app
      dockerfile: Dockerfile
    
    container_name: django_app
    restart: always

    ports:
      - "8000:8000" 

    networks:
      - app-network
    
    depends_on:
      - postgres
    
    command: sh -c "python3 project/manage.py makemigrations &&
                    python3 project/manage.py migrate &&
                    python3 project/manage.py &&
                    python3 project/manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata:

networks:
  app-network:
    driver: "bridge"
    external: false